branch-defaults:
  default:
    environment: back-end-11-dev
environment-defaults:
  back-end-11-dev:
    branch: null
    repository: null
global:
  application_name: back-end-1.1
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
