version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@3.0.0
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    working_directory: ~/udagram
    docker:
      - image: cimg/node:16.13.1-browsers
    executor: aws-cli/default
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - restore_cache:
          key: udagram-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: udagram-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - aws-cli/setup
      - eb/setup      
      - run: node --version
      - checkout
      - run:
          name: frontend_install
          command: |
            npm run frontend:install
      - run:
          name: backend_install
          command: |
            npm run backend:install
      # - run:
      #     name: deploy backend
      #     command: |
      #       npm run backend:deploy
      # - run:
      #     name: deploy frontend
      #     command: |
      #       npm run frontend:deploy
      - run:
          name: frontend test
          command: |
            npm run frontend:test