version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.0.0
jobs:
  build:
    docker:
      - image: cimg/node:16.14.0
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - checkout
      - run:
          name: check node version
          command: |
            node -v
      - run:
          name: frontend_install
          command: |
            npm run frontend:install
      - run:
          name: backend_install
          command: |
            npm run backend:install
      - run:
          name: build_backend
          command: |
            npm run backend:build
      - run:
          name: build_frontend
          command: |
            npm run frontend:build
      - run:
          name: deploy backend
          command: |
            npm run backend:deploy
      - run:
          name: deploy frontend
          command: |
            npm run frontend:deploy